export {
  useSettingsManifest,
  useSettingsSection,
  useVisibleSections,
  useUserSettings,
  useUpdateUserSettings,
  useUserPreferences,
  useUpdateUserPreference,
  useTenantSettings,
  useUpdateTenantSettings,
  usePlatformSettings,
  useRequestMaintenanceOtp,
  useUpdatePlatformSettings,
  settingsKeys,
} from "./use-settings";
